### ISSUE TITLE
Error with nanocompore sampcomp 

### ISSUE THREAD

**Issue by Huanle** [tleonardi/nanocompore_pipeline#6]
Hi @tleonardi ,

I ran into an error with this command:
```
nanocompore sampcomp --file_list1 bc1.evnaln.collapse/out_eventalign_collapse.tsv,bc2.evnaln.collapse/out_eventalign_collapse.tsv,bc3.evnaln.collapse/out_eventalign_collapse.tsv --file_list2 bc4.evnaln.collapse/out_eventalign_collapse.tsv --label1 KO --label2 WT --fasta yeast_rRNA_ref.fa --outpath ./results --overwrite --nthreads 8
```

## error message:

Initialising SampComp and checking options
Only 1 replicate found for condition WT
This is not recommended. The statistics will be calculated with the logit method
Initialising Whitelist and checking options
Reading eventalign index files
        References found in index: 4
Filtering out references with low coverage
        References remaining after reference coverage filtering: 2
Starting data processing
M  0%|          | 0/2 [00:00<?, ? Processed References/s]M  0%|          | 0/2 [00:00<?, ? Processed References/s]
Loading SampCompDB
Traceback (most recent call last):
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/bin/nanocompore", line 8, in <module>
    sys.exit(main())
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/__main__.py", line 139, in main
    args.func(args)
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/__main__.py", line 174, in sampcomp_main
    db = s()
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampComp.py", line 268, in __call__
    log_level=self.__log_level)
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampCompDB.py", line 82, in __init__
    raise NanocomporeError("The result database is empty")
nanocompore.common.NanocomporeError: The result database is empty
Initialising SampComp and checking options
Only 1 replicate found for condition WT
This is not recommended. The statistics will be calculated with the logit method
Initialising Whitelist and checking options
Reading eventalign index files
        References found in index: 4
Filtering out references with low coverage
        References remaining after reference coverage filtering: 2
Starting data processing
M  0%|          | 0/2 [00:00<?, ? Processed References/s]M  0%|          | 0/2 [00:00<?, ? Processed References/s]
Loading SampCompDB
Traceback (most recent call last):
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/bin/nanocompore", line 8, in <module>
    sys.exit(main())
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/__main__.py", line 139, in main
   args.func(args)
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/__main__.py", line 174, in sampcomp_main
    db = s()
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampComp.py", line 268, in __call__
    log_level=self.__log_level)
  File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampCompDB.py", line 82, in __init__
    raise NanocomporeError("The result database is empty")
nanocompore.common.NanocomporeError: The result database is empty

## Can you help to fix it? Thanks a lot!

**Comment by tleonardi** [comment]
Cross-posting of https://github.com/tleonardi/nanocompore/issues/112. Closing.
